name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Build plugin
        run: |
          pnpm install
          pnpm run build

      - name: Package plugin
        run: |
          mkdir -p ${{ github.workspace }}/daggerheart-toolkit
          mkdir -p ${{ github.workspace }}/daggerheart-toolkit/data
          mkdir -p ${{ github.workspace }}/daggerheart-toolkit/user_compendium

          # Copy main files
          cp main.js manifest.json styles.css ${{ github.workspace }}/daggerheart-toolkit/

          # Copy and rename CSS file from main.css to styles.css
          # cp main.css ${{ github.workspace }}/daggerheart-toolkit/styles.css

          # Copy data directory
          cp -r data/* ${{ github.workspace }}/daggerheart-toolkit/data/

          # Create an empty .gitkeep file in user_compendium to ensure it's included
          touch ${{ github.workspace }}/daggerheart-toolkit/user_compendium/.gitkeep

          cd ${{ github.workspace }}
          tag="${GITHUB_REF#refs/tags/}"
          zip -r daggerheart-toolkit-$tag.zip daggerheart-toolkit/

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            daggerheart-toolkit-$tag.zip
